### ISSUE TITLE
Remove the "HOME" link from top

### ISSUE THREAD

**Issue by thedevyansh** [thedevyansh/random_number#1]

**Comment by RishiRajKhanna2511** [comment]
Please assign this to me. I would love to work in this.

**Comment by thedevyansh** [comment]
> Please assign this to me. I would love to work in this.

Sure.

**Comment by RishiRajKhanna2511** [comment]
I have done the changes  Please check

**Comment by RishiRajKhanna2511** [comment]
Please merge the pull request or if any changes needs to be done , than do inform me
