### ISSUE TITLE
Make the input to submit number on pressing enter

### ISSUE THREAD

**Issue by thedevyansh** [thedevyansh/random_number#2]

**Comment by harshitsuthar77731** [comment]
assign me this i would love to contribute

**Comment by iamsahilparashar** [comment]
> assign me this i would love to contribute



> assign me this i would love to contribute

i'm new at github .Is this neccessary to request from owner because i already opened a pull request for this issue without requesting to contribute ?

**Comment by thedevyansh** [comment]
> > assign me this i would love to contribute
> 
> > assign me this i would love to contribute
> 
> i'm new at github .Is this neccessary to request from owner because i already opened a pull request for this issue without requesting to contribute ?

No, it's not necessary to ask for assigning the issue every time. You could also just acknowledge in the issue that you are working on it so that others may know about it.
