### ISSUE TITLE
Improve the way the result is shown to the user.

### ISSUE THREAD

**Issue by thedevyansh** [thedevyansh/random_number#4]

**Comment by maenad** [comment]
Can you please assign me this? I will be tinkering with it for a better look.

**Comment by thedevyansh** [comment]
> Can you please assign me this? I will be tinkering with it for a better look.

Sure. There you go.

**Comment by maenad** [comment]
I have created a PR for this issue, feel free to check it out and merge it or let me know if you would want anything different.
